### ISSUE TITLE
ボードカタログのバリエーションでmrubyにインクルードしているmrbgemを表示したい

### ISSUE THREAD

**Issue by tarosay** [kimushu/vsce-rubic#16]
内包しているmrbgem違いをバリエーションとして用意しておけば、自分が使いたいmrbgemが入っているbinファイルをボードに書き込んでもらえると思っています。
　mrbgem違いをあらかじめ用意しておくことで、ユーザさんが自分でmrubyをコンパイルしなくてもよくなるのでいいのではないかと思っています。

　ただ、リリースのData.zipの差し替えをバリエーションが増えるたびに行うことになりますが、そこは何か支障がありますでしょうか。

**Comment by kimushu** [comment]
「mrbgem違いをバリエーションで吸収する」、いいですね！
想定できていなかったですけども、バリエーションの良い使い道だと思います。

> ただ、リリースのData.zipの差し替えをバリエーションが増えるたびに行う

あるリリースが出たら、そこに含まれたバリエーションは(追加も含めて)変更すべきではないです。
(システム的には差し替え可能ですが、原則として間違ったバイナリを配布しちゃったときの救済措置という位置づけです。)

たとえば次のようなトラブルが考えられるかと。

1. ファーム作者がv1.0を公開(バリエーションはXのみ)
1. 利用者Aがv1.0を使う (この時点でAさんのPCにv1.0(旧)のデータがダウンロード)
1. ファーム作者がv1.0を**差し替え(バリエーションYを追加)**
1. 利用者Bがv1.0を使う (この時点でBさんのPCにv1.0(新)のデータがダウンロードされる)
1. Bさんがv1.0のバリエーションYを使ったプログラムを公開する (or Aさんに渡す)
1. AさんがBさんから受け取ったプログラムを動かそうとするが、v1.0(旧)には存在しないバリエーションYを指しているため動かない。

なので提案ですが、mrbgemが増えたら(バリエーションの組み合わせに差ができたら)、
そもそもバージョンアップして別のリリース扱いにしてしまってはいかがでしょう？
用意する側も、過去のリリースに遡って増えた分のビルドをするのは大変かと。

**Comment by tarosay** [comment]
そうですね。わかりました。
リリースのバージョンをあげていけばいいですね。v2.30.1 v2.30.2 とかビルドバージョンを用意すればいいかなと思いました。
　課題はbin側ですが、どのmrbgemが含まれているのか、VSCode Rubicでバリエーションを見てもらわないとわからない、という点ですね。
　これはあきらめてもらうしかないな。

**Comment by kimushu** [comment]
将来的には、Rubicで選んだリリース&バリエーションと、実際にボードに書かれているファームとの照合機能が欲しいなと思っています。
ファーム側へ自動的にmrbgem一覧を含められるといいんですが、これはmruby本家のビルド用rakeに手を入れることになりそうです。
(またはmrubyビルド時の"Included Gems"を拾ってファームに混ぜ込むようにするか。)

**Comment by tarosay** [comment]
バリエーションごとにハッシュを用意して、ファーム側にハッシュ値を返すコマンドを用意する？
mrbgem一覧を返すコマンドを用意する？
フラッシュにファームが持っている上のようなデータをjsonかxmlで吐き出すことも考えましたが、フラッシュの書き換えが増えるのも考えものだなと思っています。

**Comment by tarosay** [comment]
とりあえず、release.jsonに、このように書いておいていいでしょうか？
`
{
  "variations": [
    {
      "path": "citrus_sketch.bin",
      "name": {
        "en": "GR-CITRUS"
      },
      "description": {
        "en": "Release mruby firmware v2.19 of GR-CITRUS.",
        "ja": "GR-CITRUSのmrubyファームウェア v2.19です。"
      },
      "runtimes": [
        {
          "name": "mruby",
          "version": "1.2.0"
        }
      ],
      "mrbgems": [
        {
          "name": "mruby-math",
          "description": {
            "en": "standard Math module"
          }
        },
        {
          "name": "mruby-numeric-ext",
          "description": {
            "en": "Numeric class extension"
          }
        }
      ]
    }
  ]
}
`

**Comment by kimushu** [comment]
すみません返答がおそくなりました。
`mrbgems`は、runtimeの中のname=mrubyの要素としていれて頂けますか？
↓部分的に書くとこういう感じで。

```json
{
  "runtimes": [
    {
      "name": "mruby",
      "version": "1.2.0",
      "mrbgems": [
        {"name": "mruby-math", "description": "...."},
        {"name": "mruby-numeric-ext", "description": "...."}
      ]
    }
  ]
}
```

**Comment by kimushu** [comment]
次回バージョンアップからカタログの詳細ページに表示されます。

**Comment by kimushu** [comment]
* バリエーションリストにおけるバッジの追加
![image](https://user-images.githubusercontent.com/1642194/27758899-0b720698-5e5b-11e7-89ae-4337b9ab4e29.png)

* 詳細表示におけるランタイム説明ページの追加
![image](https://user-images.githubusercontent.com/1642194/27758896-04e200bc-5e5b-11e7-8154-caaf234772ff.png)

以上2カ所に表示することとし、本チケットをクローズします。
