### ISSUE TITLE
mrbcのコンパイルでエラーしたときに詳細を出してほしい

### ISSUE THREAD

**Issue by tarosay** [kimushu/vsce-rubic#18]
rbコードにsyntax errorがあるとき、
mrbc aborted with code=1
というエラーが出ますが、mrbcの実行では、
main.rb:9:5: syntax error, unexpected tIDENTIFIER, expecting ')'
などと、エラー内容が詳しく出ています。
この内容ほエラー表示時に出してもらえませんでしょうか。
よろしくお願いします。

**Comment by kimushu** [comment]
出力ウィンドウの「Rubic出力」に出力されています。

**Comment by tarosay** [comment]
ありがとうございます。気づいていませんでした。
見つけました。
Issueを閉じたいと思います。
