### ISSUE TITLE
Program break does not work on mac

### ISSUE THREAD

**Issue by kimushu** [kimushu/vsce-rubic#27]
- Rubic Version: 0.99.16
- VSCode Version: 1.21.1
- OS Version: mac OS High Sierra

Steps to Reproduce: 

1. Write endless program to GR-CITRUS
```ruby
loop do
  led
  delay 500
end
```
2. Start program via Rubic
3. Press "Stop debug" button

**Comment by kimushu** [comment]
Windows環境でも再現:

バージョン 1.21.1
コミット 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
日付 2018-03-14T14:46:47.128Z
シェル 1.7.9
レンダラー 58.0.3029.110
Node 7.9.0
アーキテクチャ x64

**Comment by tarosay** [comment]
macOS High Sierra
バージョン 10.13.2
MacBook (Retina, 12-inch, 2017)
プロセッサ 1.3 GHz intel Core i5

私のMac環境です。

**Comment by kimushu** [comment]
GR-CITRUS side: Closed by wakayamarb/wrbb-v2lib-firm#22
Rubic side: Closed by 476d4b98391b766cda12c02d922e23751667940f
